app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Event::listen('auth.*', function($event){ });

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);

// Registration Routes...
$this->get('register', 'Auth\AuthController@showRegistrationForm');
$this->post('register', 'Auth\AuthController@register');

//https://mattstauffer.co/blog/the-auth-scaffold-in-laravel-5-2
Route::get('/', ['middleware' => 'auth', 'as' => 'dashboard', 'uses' => 'DashboardController@index']);

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('/profile', ['middleware' => 'auth', 'as' => 'user_profile', 'uses' => 'UserController@profile']);

Route::post('/profile/{user_id}/update', ['middleware' => 'auth', 'as' => 'user_profile_update', 'uses' => 'UserController@update_profile']);

// Password Reset ejZ5yr
Route::get('/reset_user_password', ['as' => 'reset_user_password', 'uses' => 'UserController@reset_user_password']);
Route::post('/reset_user_confirm', ['as' => 'reset_user_confirm', 'uses' => 'UserController@reset_user_confirm']);

Route::group(['prefix' => 'api'], function () {
	Route::group(['prefix' => 'notification'], function () {
		Route::get('request', ['as' => 'request_notification', 'uses' => 'ServiceRequestController@notification']);
	});
	Route::group(['prefix' => 'search'], function () {
		//Route::get('category', ['as' => 'item_category_search', 'uses' => 'ItemCategoryController@search']);
		Route::get('item', ['as' => 'item_search', 'uses' => 'ItemController@search']);
	});
});

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function () {

	Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
	
	Route::group(['prefix' => 'user', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'users', 'uses' => 'UserController@index']);
		Route::get('create', ['as' => 'user_create', 'uses' => 'UserController@create']);
		Route::post('store', ['as' => 'user_store', 'uses' => 'UserController@store']);
		Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'UserController@edit']);
		Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'UserController@update']);

		Route::get('{user_id}/penalties', ['as' => 'user_penalties', 'uses' => 'UserController@penalties']);
	});

	Route::group(['prefix' => 'reports', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'reports', 'uses' => 'ReportController@index']);
		Route::post('generate', ['as' => 'report_generate', 'uses' => 'ReportController@generate']);
	});

	Route::group(['prefix' => 'dss', 'middleware' => 'admin'], function() {
		Route::get('/', ['as' => 'puchase_dss', 'uses' => 'HomeController@purchasedss']);
		Route::get('{id}/user', ['as' => 'user_dss', 'uses' => 'HomeController@userdss']);
		Route::get('{id}/item', ['as' => 'item_dss', 'uses' => 'HomeController@itemdss']);
	});

	Route::group(['prefix' => 'item', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'item', 'uses' => 'ItemController@index']);
		Route::get('create', ['as' => 'item_create', 'uses' => 'ItemController@create']);
		Route::post('store', ['as' => 'item_store', 'uses' => 'ItemController@store']);
		Route::get('{item_id}/edit', ['as' => 'item_edit', 'uses' => 'ItemController@edit']);
		Route::post('{item_id}/update', ['as' => 'item_update', 'uses' => 'ItemController@update']);
		Route::get('{item_id}/qrprint', ['as' => 'item_qrprint', 'uses' => 'ItemController@qrprint']);

		Route::group(['prefix' => 'category'], function () {
			Route::get('/', ['as' => 'item_category', 'uses' => 'ItemCategoryController@index']);
			Route::get('create', ['as' => 'item_category_create', 'uses' => 'ItemCategoryController@create']);
			Route::post('store', ['as' => 'item_category_store', 'uses' => 'ItemCategoryController@store']);
			Route::get('{item_category_id}/edit', ['as' => 'item_category_edit', 'uses' => 'ItemCategoryController@edit']);
			Route::post('{item_category_id}/update', ['as' => 'item_category_update', 'uses' => 'ItemCategoryController@update']);
		});

		Route::group(['prefix' => 'brand'], function () {
			Route::get('/', ['as' => 'item_brand', 'uses' => 'ItemBrandController@index']);
			Route::get('create', ['as' => 'item_brand_create', 'uses' => 'ItemBrandController@create']);
			Route::post('store', ['as' => 'item_brand_store', 'uses' => 'ItemBrandController@store']);
			Route::get('{item_brand_id}/edit', ['as' => 'item_brand_edit', 'uses' => 'ItemBrandController@edit']);
			Route::post('{item_brand_id}/update', ['as' => 'item_brand_update', 'uses' => 'ItemBrandController@update']);
		});
	});

	Route::group(['prefix' => 'service-request'], function () {
		Route::get('/', ['as' => 'service_request', 'uses' => 'ServiceRequestController@index']);
		Route::get('{id}/deny', ['as' => 'service_request_deny', 'uses' => 'ServiceRequestController@request_deny']);
		Route::get('{id}/cancel', ['as' => 'service_request_cancel', 'uses' => 'ServiceRequestController@request_cancel']);

		Route::post('{id}/approval', ['as' => 'service_request_approval', 'uses' => 'ServiceRequestController@request_approval']);

		Route::get('{id}/return', ['as' => 'service_request_return', 'uses' => 'ServiceRequestController@request_return']);

		Route::get('{id}/receipt', ['as' => 'service_request_receipt', 'uses' => 'ServiceRequestController@request_receipt']);

		Route::get('{id}/closed', ['as' => 'service_request_closed', 'uses' => 'ServiceRequestController@request_closed']);

		Route::group(['prefix' => 'item'], function () {
			Route::get('{id}', ['as' => 'service_request_items', 'uses' => 'ServiceRequestController@request']);
			Route::get('{id}/deny', ['as' => 'service_request_items_deny', 'uses' => 'ServiceRequestController@item_deny']);
			Route::get('{id}/cancel', ['as' => 'service_request_items_cancel', 'uses' => 'ServiceRequestController@item_cancel']);
			Route::get('{id}/approved', ['as' => 'service_request_items_approved', 'uses' => 'ServiceRequestController@item_approved']);

			Route::get('{request_id}/{brand_id}/{category_id}/assign', ['as' => 'service_request_assign_items', 'uses' => 'ServiceRequestController@assign_item_request']);
			Route::post('{request_id}/{brand_id}/{category_id}/assign-submit', ['as' => 'service_request_assign_items_submit', 'uses' => 'ServiceRequestController@assign_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return', ['as' => 'service_request_return_item', 'uses' => 'ServiceRequestController@return_item_request']);
			Route::post('{request_borrowed_item_id}/return-submit', ['as' => 'service_request_return_item_submit', 'uses' => 'ServiceRequestController@return_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return-closed', ['as' => 'service_request_return_item_closed', 'uses' => 'ServiceRequestController@return_item_request_closed']);
			Route::post('{request_borrowed_item_id}/return-closed-submit', ['as' => 'service_request_return_item_closed_submit', 'uses' => 'ServiceRequestController@return_item_request_closed_submit']);
		});

		Route::get('create', ['as' => 'service_request_create', 'uses' => 'ServiceRequestController@create']);
		Route::post('store', ['as' => 'service_request_store', 'uses' => 'ServiceRequestController@store']);
		#Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'ServiceRequestController@edit']);
		#Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'ServiceRequestController@update']);
	});
});	

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use App\ServiceRequestReturnItem;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'active', 'reset'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setActiveAttribute($value)
    {
        return $value == 'on' ? 1 : 0 ;
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile', 'id', 'user_id');
    }

    public function requests()
    {
        return $this->hasMany('App\ServiceRequest');
    }

    public function getActiveStatusAttribute($value)
    {
        return ($this->active == 1) ? "Yes" : "No";
    }

    public function getRoleAliasAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "Administrator";
                break;
            case 'basic':
                return "Basic User";
                break;
            default:
                return "Unassigned";
                break;
        }
    }

    public function getActiveStatusLabelAttribute($value)
    {
        return ($this->active == 1) ? "<span class='label primary'>Yes</span>" : "<span class='label secondary'>No</span>";
    }

    public function getRoleAdminLabelAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "<span class='label primary'>Yes</span>";
                break;
            case 'basic':
                return "<span class='label secondary'>No</span>";
                break;
            default:
                return "<span class='label warning'>N/A</span>";
                break;
        }
    }

    public function getTotalPenaltiesAttribute()
    {
        $id = $this->id;

        #$count = ServiceRequestReturnItem::whereRequestReturnStatusId(2)->count();
        $count = ServiceRequestReturnItem::leftJoin('request', 'request_return_item.request_id', '=', 'request.id')
        ->where('request.user_id', $id)
        ->where('request_return_item.request_return_status_id', 2)
        ->count();

        return $count;
    }

    public function getCreatedAtAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
}

resources/views/users/form.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
  <div class="row" >
    <div class="small-6 small-centered columns"> 
      @include('layouts.message')
    </div>
  </div>
  <!-- Container Title -->
  <div class="row" >
   
      @if(!Request::is('portal/user/*/edit'))
          <div class="small-4 small-centered columns">
              <h4>New User</h4>
          </div>
      @else
          <div class="small-12 small-centered columns">
              <nav aria-label="You are here:" role="navigation">
                <ul class="breadcrumbs">
                  <li style="font-size: 12pt;"><a href="{{ route('users') }}">Users</a></li>
                  <li style="font-size: 12pt;">
                    <span class="show-for-sr">Current: </span> Edit
                  </li>
                </ul>
              </nav>
          </div>
      @endif
  </div>
  <!-- Container Title -->
<form action="{{ $action }}" method="post">
  <!-- Container Content -->
@if(!Request::is('portal/user/*/edit'))
     @include('users.profile.account')  
@else
<ul class="tabs" data-deep-link="true" data-update-history="true" data-deep-link-smudge="true" data-deep-link-smudge="500" data-tabs id="deeplinked-tabs">
  <li class="tabs-title is-active"><a href="#personal" aria-selected="true">Personal Information</a></li>
  <li class="tabs-title"><a href="#account">Account Settings</a></li>
</ul>
  <div class="tabs-content" data-tabs-content="deeplinked-tabs" style="margin-bottom:20px;" >
    <div class="tabs-panel is-active" id="personal">
      <p>
         @include('users.profile.personal')
      </p>
    </div>
    <div class="tabs-panel" id="account">
      <p>
        @include('users.profile.account')     
      </p>
    </div>
  </div>
@endif   
  <div class="row">
    <div class="small-2 small-centered columns">
      <button class="button primary" name="save" value="true">Save</button>
      <a href="{{ route('users') }}" class="button secondary">Back</a>
    </div>
  </div>
  {!! csrf_field() !!}
</form>

  <!-- Container Content -->
<script type="text/javascript">
</script>
<!-- Stops Container -->
@stop

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
        
  <!-- Container Title -->
  <div class="row" >
    <div class="medium-12 columns">
      <h4>Users</h4>
    </div>
  </div>
  <!-- Container Title -->

  @include('layouts.message')

  <!-- Container Content -->
  <div class="row" >
    <div class="medium-12 columns">
      <form action="" method="get">
        <div class="row">
          <div class="medium-4 columns">
            <div class="input-group">
              <input class="input-group-field" type="text" name="search" value="{{ $search }}">
              <div class="input-group-button">
                <button type="submit" class="button"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
          <div class="medium-8 columns">&nbsp;</div>
        </div>
      </form>
      <table class="hover">
        <thead>
          <th width="5%"><a href="{{ route('user_create') }}" title="Add User"><i class="fa fa-plus"></i></a></th>
          <th width="5%">ID</th>          
          <th width="10%">Username</th>
          <th width="40%">Name</th>
          <th width="10%" align="center">Penalties</th>
          <th width="2%">Admin</th>
          <th width="2%">Active</th>
        </thead>
        <tbody>
          @foreach($users as $user)
          <tr>
            <td><a href="{{ route('user_edit', $user->id) }}" title="Edit"><i class="fa fa-edit"></i></a></td>
            <td>{{ $user->id }}</td>            
            <td>{{ $user->email }}</td>
            <td>{{ $user->name }}</td>
            <td align="center"><a href="{{ route('user_penalties', $user->id) }}">{{ $user->total_penalties }}</a></td>
            <td align="center">{!! $user->role_admin_label !!}</td>
            <td align="center">{!! $user->active_status_label !!}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
        {!! $users->render() !!}
    </div>
  </div>
  <!-- Container Content -->
        
<!-- Stops Container -->
@stop

resources/views/users/penalties.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
        
  <!-- Container Title -->
  <div class="row" >
    <div class="medium-12 columns">
      <h4><a href="{{ route('users') }}">Users</a> Penlaties</h4>
    </div>
  </div>
  <!-- Container Title -->

  @include('layouts.message')

  <!-- Container Content -->
  <div class="row" >
    <div class="medium-12 columns">
      <table class="hover">
        <thead>
          <th width="20%">ISBN</th>          
          <th width="30%">Name</th>
          <th width="20%">Brand</th>
          <th width="20%">Category</th>
          <th width="10%">Status</th>
        </thead>
        <tbody>
          @foreach($rows as $row)
          <tr>
            <td>{{ $row->isbn }}</td>            
            <td>{{ $row->item_name }}</td>
            <td>{{ $row->brand_name }}</td>
            <td>{!! $row->category_name !!}</td>
            <td>{!! $row->status_name !!}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
        {!! $rows->render() !!}
    </div>
  </div>
  <!-- Container Content -->
        
<!-- Stops Container -->
@stop