app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Event::listen('auth.*', function($event){ });

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);

// Registration Routes...
$this->get('register', 'Auth\AuthController@showRegistrationForm');
$this->post('register', 'Auth\AuthController@register');

//https://mattstauffer.co/blog/the-auth-scaffold-in-laravel-5-2
Route::get('/', ['middleware' => 'auth', 'as' => 'dashboard', 'uses' => 'DashboardController@index']);

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('/profile', ['middleware' => 'auth', 'as' => 'user_profile', 'uses' => 'UserController@profile']);

Route::post('/profile/{user_id}/update', ['middleware' => 'auth', 'as' => 'user_profile_update', 'uses' => 'UserController@update_profile']);

// Password Reset ejZ5yr
Route::get('/reset_user_password', ['as' => 'reset_user_password', 'uses' => 'UserController@reset_user_password']);
Route::post('/reset_user_confirm', ['as' => 'reset_user_confirm', 'uses' => 'UserController@reset_user_confirm']);

Route::group(['prefix' => 'api'], function () {
	Route::group(['prefix' => 'notification'], function () {
		Route::get('request', ['as' => 'request_notification', 'uses' => 'ServiceRequestController@notification']);
	});
	Route::group(['prefix' => 'search'], function () {
		//Route::get('category', ['as' => 'item_category_search', 'uses' => 'ItemCategoryController@search']);
		Route::get('item', ['as' => 'item_search', 'uses' => 'ItemController@search']);
	});
});

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function () {

	Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
	
	Route::group(['prefix' => 'user', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'users', 'uses' => 'UserController@index']);
		Route::get('create', ['as' => 'user_create', 'uses' => 'UserController@create']);
		Route::post('store', ['as' => 'user_store', 'uses' => 'UserController@store']);
		Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'UserController@edit']);
		Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'UserController@update']);

		Route::get('{user_id}/penalties', ['as' => 'user_penalties', 'uses' => 'UserController@penalties']);
	});

	Route::group(['prefix' => 'reports', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'reports', 'uses' => 'ReportController@index']);
		Route::post('generate', ['as' => 'report_generate', 'uses' => 'ReportController@generate']);
	});

	Route::group(['prefix' => 'dss', 'middleware' => 'admin'], function() {
		Route::get('/', ['as' => 'puchase_dss', 'uses' => 'HomeController@purchasedss']);
		Route::get('{id}/user', ['as' => 'user_dss', 'uses' => 'HomeController@userdss']);
		Route::get('{id}/item', ['as' => 'item_dss', 'uses' => 'HomeController@itemdss']);
	});

	Route::group(['prefix' => 'item', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'item', 'uses' => 'ItemController@index']);
		Route::get('create', ['as' => 'item_create', 'uses' => 'ItemController@create']);
		Route::post('store', ['as' => 'item_store', 'uses' => 'ItemController@store']);
		Route::get('{item_id}/edit', ['as' => 'item_edit', 'uses' => 'ItemController@edit']);
		Route::post('{item_id}/update', ['as' => 'item_update', 'uses' => 'ItemController@update']);
		Route::get('{item_id}/qrprint', ['as' => 'item_qrprint', 'uses' => 'ItemController@qrprint']);

		Route::group(['prefix' => 'category'], function () {
			Route::get('/', ['as' => 'item_category', 'uses' => 'ItemCategoryController@index']);
			Route::get('create', ['as' => 'item_category_create', 'uses' => 'ItemCategoryController@create']);
			Route::post('store', ['as' => 'item_category_store', 'uses' => 'ItemCategoryController@store']);
			Route::get('{item_category_id}/edit', ['as' => 'item_category_edit', 'uses' => 'ItemCategoryController@edit']);
			Route::post('{item_category_id}/update', ['as' => 'item_category_update', 'uses' => 'ItemCategoryController@update']);
		});

		Route::group(['prefix' => 'brand'], function () {
			Route::get('/', ['as' => 'item_brand', 'uses' => 'ItemBrandController@index']);
			Route::get('create', ['as' => 'item_brand_create', 'uses' => 'ItemBrandController@create']);
			Route::post('store', ['as' => 'item_brand_store', 'uses' => 'ItemBrandController@store']);
			Route::get('{item_brand_id}/edit', ['as' => 'item_brand_edit', 'uses' => 'ItemBrandController@edit']);
			Route::post('{item_brand_id}/update', ['as' => 'item_brand_update', 'uses' => 'ItemBrandController@update']);
		});
	});

	Route::group(['prefix' => 'service-request'], function () {
		Route::get('/', ['as' => 'service_request', 'uses' => 'ServiceRequestController@index']);
		Route::get('{id}/deny', ['as' => 'service_request_deny', 'uses' => 'ServiceRequestController@request_deny']);
		Route::get('{id}/cancel', ['as' => 'service_request_cancel', 'uses' => 'ServiceRequestController@request_cancel']);

		Route::post('{id}/approval', ['as' => 'service_request_approval', 'uses' => 'ServiceRequestController@request_approval']);

		Route::get('{id}/return', ['as' => 'service_request_return', 'uses' => 'ServiceRequestController@request_return']);

		Route::get('{id}/receipt', ['as' => 'service_request_receipt', 'uses' => 'ServiceRequestController@request_receipt']);

		Route::get('{id}/closed', ['as' => 'service_request_closed', 'uses' => 'ServiceRequestController@request_closed']);

		Route::group(['prefix' => 'item'], function () {
			Route::get('{id}', ['as' => 'service_request_items', 'uses' => 'ServiceRequestController@request']);
			Route::get('{id}/deny', ['as' => 'service_request_items_deny', 'uses' => 'ServiceRequestController@item_deny']);
			Route::get('{id}/cancel', ['as' => 'service_request_items_cancel', 'uses' => 'ServiceRequestController@item_cancel']);
			Route::get('{id}/approved', ['as' => 'service_request_items_approved', 'uses' => 'ServiceRequestController@item_approved']);

			Route::get('{request_id}/{brand_id}/{category_id}/assign', ['as' => 'service_request_assign_items', 'uses' => 'ServiceRequestController@assign_item_request']);
			Route::post('{request_id}/{brand_id}/{category_id}/assign-submit', ['as' => 'service_request_assign_items_submit', 'uses' => 'ServiceRequestController@assign_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return', ['as' => 'service_request_return_item', 'uses' => 'ServiceRequestController@return_item_request']);
			Route::post('{request_borrowed_item_id}/return-submit', ['as' => 'service_request_return_item_submit', 'uses' => 'ServiceRequestController@return_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return-closed', ['as' => 'service_request_return_item_closed', 'uses' => 'ServiceRequestController@return_item_request_closed']);
			Route::post('{request_borrowed_item_id}/return-closed-submit', ['as' => 'service_request_return_item_closed_submit', 'uses' => 'ServiceRequestController@return_item_request_closed_submit']);
		});

		Route::get('create', ['as' => 'service_request_create', 'uses' => 'ServiceRequestController@create']);
		Route::post('store', ['as' => 'service_request_store', 'uses' => 'ServiceRequestController@store']);
		#Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'ServiceRequestController@edit']);
		#Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'ServiceRequestController@update']);
	});
});	

app/ServiceRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \Carbon\Carbon;
use App\User;
use App\ServiceRequestStatus;

class ServiceRequest extends Model
{
    public $table = 'request';
    public $fillable = ['request_status_id', 'request_datetime', 'return_datetime', 'remarks', 'user_id', 'created_at', 'updated_at'];
    public $timestamps = true;

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function request_status()
    {
        return $this->hasOne('App\ServiceRequestStatus', 'id', 'request_status_id');
    }

    public function request_item()
    {
        return $this->belongsTo('App\ServiceRequestItem', 'id', 'request_id');
    }

    public function request_items()
    {
        return $this->hasMany('App\ServiceRequestItem', 'request_id', 'id');
    }

    public function request_remarks()
    {
        return $this->hasOne('App\ServiceRequestRemarks', 'id', 'request_id');
    }

    public function setRequestDatetimeAttribute($value)
    {
    	$this->attributes['request_datetime'] = date('Y-m-d H:i:s', strtotime($value));
    }

    public function setReturnDatetimeAttribute($value)
    {
    	$this->attributes['return_datetime'] = date('Y-m-d H:i:s', strtotime($value));
    }

    public function getRequesterAttribute($value)
    {
    	$row = User::whereId($this->user_id)->first();
    	return $row->name;
    }

    /*public function getRequestStatusAttribute($value)
    {
    	$row = ServiceRequestStatus::whereId($this->request_status_id)->first();
    	return $row->name;
    }*/
    public function getCreatedAtAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
   public function getRequestDatetimeAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
      public function getReturnDatetimeAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use App\ServiceRequestReturnItem;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'active', 'reset'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setActiveAttribute($value)
    {
        return $value == 'on' ? 1 : 0 ;
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile', 'id', 'user_id');
    }

    public function requests()
    {
        return $this->hasMany('App\ServiceRequest');
    }

    public function getActiveStatusAttribute($value)
    {
        return ($this->active == 1) ? "Yes" : "No";
    }

    public function getRoleAliasAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "Administrator";
                break;
            case 'basic':
                return "Basic User";
                break;
            default:
                return "Unassigned";
                break;
        }
    }

    public function getActiveStatusLabelAttribute($value)
    {
        return ($this->active == 1) ? "<span class='label primary'>Yes</span>" : "<span class='label secondary'>No</span>";
    }

    public function getRoleAdminLabelAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "<span class='label primary'>Yes</span>";
                break;
            case 'basic':
                return "<span class='label secondary'>No</span>";
                break;
            default:
                return "<span class='label warning'>N/A</span>";
                break;
        }
    }

    public function getTotalPenaltiesAttribute()
    {
        $id = $this->id;

        #$count = ServiceRequestReturnItem::whereRequestReturnStatusId(2)->count();
        $count = ServiceRequestReturnItem::leftJoin('request', 'request_return_item.request_id', '=', 'request.id')
        ->where('request.user_id', $id)
        ->where('request_return_item.request_return_status_id', 2)
        ->count();

        return $count;
    }

    public function getCreatedAtAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
}

resources/views/request/assign.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
        
  <!-- Container Title -->
<div class="row" >
    <div class="medium-12 columns">
    	<h4><a href="{{ route('service_request_items', $id) }}">Service Request</a> # <u>{{ $id }}</u></h4>
    </div>
</div>
  <!-- Container Title -->

  @include('layouts.message')

  <!-- Container Content -->
<div class="row">
	<div class="medium-6 columns">
		<div class="row">
		    <div class="medium-5 columns">Requester</div>
		    <div class="medium-7 columns">{{ $request->user->name }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Request Datetime</div>
		    <div class="medium-7 columns">{{ $request->request_datetime }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Return Datetime</div>
		    <div class="medium-7 columns">{{ $request->return_datetime }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Status</div>
		    <div class="medium-7 columns">{{ $request_item->request_item_status->name }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Date Created</div>
		    <div class="medium-7 columns">{{ $request->created_at }}</div>
		</div>
	</div>
	<div class="medium-6 columns">
		<div class="row">
		    <div class="medium-2 columns">Remarks</div>
		    <div class="medium-10 columns">{{ $request->remarks }}</div>
		</div>
	</div>
</div>

<form action="{{ route('service_request_assign_items_submit', ['request_id'=>$id, 'brand_id'=>$brand_id, 'category_id'=>$category_id]) }}" method="post">
	<div class="row" >
	    <div class="medium-12 columns">
	      	<table class="hover">
		        <thead>
					<th width="5%"><input type="checkbox" id="checkAll"></th>
					<th width="15%">ISBN</th>
					<th width="20%">Brand</th>
					<th width="20%">Category</th>
					<th width="40%">Item Name</th>
		        </thead>
		        <tbody>
		        	@foreach($rows as $row)

			        	<?php

			        	$condition_1 = App\ServiceRequestBorrowedItem::whereRequestId($request->id)->whereItemId($row->id)->count() != 0;
			        	$condition_2 = App\ServiceRequestBorrowedItem::whereItemId($row->id)->count() == 0;

                		$total_quantity = App\Item::where('item_category_id', $row->item_category_id)->where('item_brand_id', $row->item_brand_id)->count();

		                $items = App\ServiceRequestItem::leftJoin('request', 'request.id', '=', 'request_item.request_id')
		                ->where('request_brand_status_id', 2)
		                ->where('request_status_id', 2)
		                ->where('item_category_id', $row->item_category_id)
		                ->where('item_brand_id', $row->item_brand_id)
		                ->get();

		                foreach ($items as $item)
		                {
		                    if($item->request_datetime <= $from && $item->return_datetime >= $from)
		                    {
		                        $total_quantity -= $item->quantity;
		                    }
		                    elseif($item->request_datetime <= $to && $item->return_datetime >= $to)
		                    {
		                        $total_quantity -= $item->quantity;
		                    }
		                    elseif($from <= $item->request_datetime && $to >= $item->request_datetime)
		                    {
		                        $total_quantity -= $item->quantity;
		                    }
		                    elseif($from <= $item->return_datetime && $to >= $item->return_datetime)
		                    {
		                        $total_quantity -= $item->quantity;
		                    }
		                }

			        	?>

			        	@if($condition_1)
				        	<tr>
					            <td>
					            	@if($total_quantity > 0)
						            	@if($request_item->request_brand_status_id == 1)
						            		<input type="checkbox" name="item[{{ $row->id }}]" value="1">
						            	@elseif($request_item->request_brand_status_id == 2)
						            		@if(App\ServiceRequestBorrowedItem::whereRequestId($id)->whereItemId($row->id)->count() > 0)
						            			<i class="fa fa-check"></i>
						            		@endif
						            	@endif
					            	@endif
					            </td>
					            <td>{{ $row->isbn }}</td>
					            <td>{{ $row->brand->name }}</td>
					            <td>{{ $row->category->name }}</td>
					            <td>{{ $row->name }}</td>
				        	</tr>
				        @elseif($condition_2)
				        	@if($request_item->request_brand_status_id == 1)
				        	<tr>
					            <td>
					            	@if($total_quantity > 0)
						            	@if($request_item->request_brand_status_id == 1)
						            		<input type="checkbox" name="item[{{ $row->id }}]" value="1">
						            	@elseif($request_item->request_brand_status_id == 2)
						            		@if(App\ServiceRequestBorrowedItem::whereRequestId($id)->whereItemId($row->id)->count() > 0)
						            			<i class="fa fa-check"></i>
						            		@endif
						            	@endif
					            	@endif
					            </td>
					            <td>{{ $row->isbn }}</td>
					            <td>{{ $row->brand->name }}</td>
					            <td>{{ $row->category->name }}</td>
					            <td>{{ $row->name }}</td>
				        	</tr>
			        		@endif
			        	@endif

		        	@endforeach
		        </tbody>
	      	</table>
	    </div>
	</div>
	<div class="row">
		<div class="medium-12 columns">
			@if($request_item->request_brand_status_id == 1)
			<button type="submit" class="button success">Submit</button>
			@endif
	        {!! csrf_field() !!}
		</div>
	</div>
</form>
<!-- Container Content -->
<script type="text/javascript">
function confirmation(url, caption)
{
	if(confirm('Are you sure to ' + caption + ' this item?') == true)
	{
		window.location.replace(url);
		return true;
	}
}

$(function(){
	$('#checkAll').change(function(){
		$('input:checkbox').not(this).prop('checked', this.checked);
	});
});
</script>
<!-- Stops Container -->
@stop

resources/views/request/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
        
  <!-- Container Title -->
<style type="text/css">

.legend-pending
{
	background-color:#cccccc!important;
}
.legend-approved
{
	background-color:#77dd77!important;
}
.legend-closed
{
	background-color:#b0b0ff!important;
}
.legend-denied
{
	background-color:#ffb0b0!important;
}
.legend-cancelled
{
	background-color:#dd77dd!important;
}
</style>

<div class="row" >
    <div class="medium-12 columns">
    	<h4>Service Request</h4>
    </div>
</div>
  <!-- Container Title -->

  @include('layouts.message')

  <!-- Container Content -->
<div class="row" >
    <div class="medium-12 columns">
	    <div class="row">
	      	<div class="medium-5 columns">
				<form action="" method="get">
			        <div class="row">
			        	<div class="medium-8 columns">
			            	<select id="status" name="status">
			            		<option value="">All</option>
			            		@foreach(\App\ServiceRequestStatus::get() as $row)
			            			<option value="{{ $row->id }}">{{ $row->name }}</option>
			            		@endforeach
			            	</select>
			        	</div>
			        	<div class="column-4 columns">&nbsp;</div>
			        </div>
			        <div class="row">
			        	<div class="medium-6 columns">
			            	<input class="input-group-field" type="text" name="search" value="{{ $search }}">
			        	</div>
			        	<div class="medium-2 columns">
			            	<button type="submit" class="button"><i class="fa fa-search"></i></button>
			        	</div>
			        	<div class="column-4 columns">&nbsp;</div>
			        </div>

			        <!--div class="input-group">
			        	<input class="input-group-field" type="text" name="search" value="{{ $search }}">
			        	<div class="input-group-button">
			            	<button type="submit" class="button"><i class="fa fa-search"></i></button>
			        	</div>
			        </div-->
				</form>
			</div>
			<div class="medium-7 columns">
				<ul class="no-bullet">
					<li><strong>Legend</strong></li>
					@foreach($legend as $v)
						@if($v->name == 'Approved')
							<li class="legend-approved">{{ $v->name }}</li>
						@elseif($v->name == 'Pending')
							<li class="legend-pending">{{ $v->name }}</li>
						@elseif($v->name == 'Closed')
							<li class="legend-closed">{{ $v->name }}</li>
						@elseif($v->name == 'Denied')
							<li class="legend-denied">{{ $v->name }}</li>
						@elseif($v->name == 'Cancelled')
							<li class="legend-cancelled">{{ $v->name }}</li>
						@endif
					@endforeach
				</ul>
			</div>
	    </div>
      	<table class="hover">
	        <thead>
	          <th width="8%">
	            <a href="{{ route('service_request_create') }}" title="Add Item"><i class="fa fa-plus"></i></a>
	          </th>
	          <th width="10%">Request #</th>
	          <th width="30%">Requester</th>
	          <th width="20%">Request DateTime</th>
	          <th width="20%">Return DateTime</th>
	          <th width="12%">Status</th>
	        </thead>
	        <tbody>
	          @foreach($service_request as $row)
				@if($row->request_status_id == 2)
				<tr class="legend-approved">
				@elseif($row->request_status_id == 1)
				<tr class="legend-pending">
				@elseif($row->request_status_id == 5)
				<tr class="legend-closed">
				@elseif($row->request_status_id == 4)
				<tr class="legend-denied">
				@elseif($row->request_status_id == 3)
				<tr class="legend-cancelled">
				@endif
		            <td>
		            	@if($row->request_status_id == 2)
			            	<a href="{{ route('service_request_return', $row->request_id) }}" title="Return Requested Item"><i class="fa fa-refresh"></i></a>
			            	<a target="_blank" href="{{ route('service_request_receipt', $row->request_id) }}"> <i class="fa fa-print"></i></a>
		              	@else
		              		<a href="{{ route('service_request_items', $row->request_id) }}" title="Open Ticket"><i class="fa fa-tag"></i></a>
		              	@endif
		            	
		            	@can('admin-access')
			              	@if(in_array($row->request_status_id, [1]))
				            <a href="javascript:void(0)" onclick="confirmation('{{ route('service_request_deny', [$row->request_id]) }}', 'deny')" title="Deny Request?"><i class="fa fa-times"></i></a>
			            	@endif
		            	@endcan

			            @if(Auth::user()->request_id == $row->user_id && in_array($row->request_status_id, [1]))
			            	<a href="javascript:void(0)" onclick="confirmation('{{ route('service_request_cancel', [$row->request_id]) }}', 'cancel')" title="Cancel Request?"><i class="fa fa-ban"></i></a>
		            	@endif
		            </td>
		            <td>{{ $row->request_id }}</td>
		            <td>{{ $row->requester }}</td>
		            <td>{{ $row->request_datetime }}</td>
		            <td>{{ $row->return_datetime }}</td>
		            <td>{{ $row->request_status->name }}</td>
		          </tr>
	          @endforeach
	        </tbody>
      	</table>
        {!! $service_request->appends([ 'status'=>$status, 'search'=>$search ])->render() !!}
    </div>
</div>
<!-- Container Content -->
<script type="text/javascript">
$(function(){
	$('#status').val('<?php echo $status; ?>');
});
function confirmation(url, caption)
{
	if(confirm('Are you sure to ' + caption + ' this request?') == true)
	{
		window.location.replace(url);
		return true;
	}
}
</script>
<!-- Stops Container -->
@stop

resources/views/request/request.blade.php
@extends('layouts.app')

@section('content')
<!-- Starts Container -->
        
  <!-- Container Title -->
<div class="row" >
    <div class="medium-12 columns">
    	<h4><a href="{{ route('service_request') }}">Service Request</a> # <u>{{ $id }}</u></h4>
    </div>
</div>
  <!-- Container Title -->

  @include('layouts.message')

  <!-- Container Content -->
<div class="row">
	<div class="medium-6 columns">
		<div class="row">
		    <div class="medium-5 columns">Requester</div>
		    <div class="medium-7 columns">{{ $request->user->name }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Request Datetime</div>
		    <div class="medium-7 columns">{{ $request->request_datetime }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Return Datetime</div>
		    <div class="medium-7 columns">{{ $request->return_datetime }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Status</div>
		    <div class="medium-7 columns">{{ $request->request_status->name }}</div>
		</div>
		<div class="row">
		    <div class="medium-5 columns">Date Created</div>
		    <div class="medium-7 columns">{{ $request->created_at }}</div>
		</div>
	</div>
	<div class="medium-6 columns">
		<div class="row">
		    <div class="medium-2 columns">Remarks</div>
		    <div class="medium-10 columns">{{ $request->remarks }}</div>
		</div>
	</div>
</div>

<div class="row" >
    <div class="medium-12 columns">
      	<table class="hover">
	        <thead>
				<th width="10%"></th>
				<th width="65%">Item Name</th>
				<th width="10%">Quantity</th>
				<th width="15%">Status</th>
	        </thead>
	        <tbody>
	        	@foreach($rows as $row)
	        		<?php
	        		$item = App\Item::whereItemBrandId($row->item_brand_id)->whereItemCategoryId($row->item_category_id)->first();
	        		?>
			        	<tr>
				            <td>
				            	@if($request->request_status_id == 1)
				            		<a href="{{ route('service_request_assign_items', ['request_id'=>$row->request_id, 'brand_id'=>$row->item_brand_id, 'category_id'=>$row->item_category_id]) }}" title="Assign Item"><i class="fa fa-paperclip"></i></a>
				            		@if($row->request_brand_status_id == 1)
					            		@if(Auth::user()->id == $request->user_id)
						            		@if(in_array($request->request_status_id, [1, 2, 4]))
						              			<a href="javascript:void(0)" onclick="confirmation('{{ route('service_request_items_cancel', [$row->id]) }}', 'cancel')" title="Cancel item?"><i class="fa fa-ban"></i></a>
						            		@endif
						            	@endif
				            		@endif

					            	@can('admin-access')
						              	@if(in_array($row->request_brand_status_id, [1]))
							            <a href="javascript:void(0)" onclick="confirmation('{{ route('service_request_items_deny', [$row->id]) }}', 'deny')" title="Deny item?"><i class="fa fa-times"></i></a>
						            	@endif
					            	@endcan
				            	@endif
				            </td>
				            <td>{{ $item->brand->name . ' - ' . $item->category->name }}</td>
				            <td>{{ $row->quantity }}</td>
				            <td>{{ $row->request_item_status->name }}</td>
			        	</tr>
	        	@endforeach
	        </tbody>
      	</table>
    </div>
</div>
@if($request->request_status_id == 1)
<hr />
<div class="row">
	<div class="medium-6 columns">
		<form action="{{ route('service_request_approval', $request->id) }}" method="post">
		    <div class="row">
				<div class="medium-12 columns">
					<label for="remarks" class="text-left">Remarks</label>
					<textarea id="remarks" name="remarks" rows="10"></textarea>
				</div>
		    </div>
			<div class="row">
				<div class="medium-12 columns">
				<button class="button success" name="approved" value="2"><i class="fa fa-check"></i> Approved</button>
				<button class="button alert" name="denied" value="4"><i class="fa fa-times"></i> Deny</button>
					<a href="{{ route('service_request') }}" class="button secondary">Back</a>
				</div>
			</div>
			{!! csrf_field() !!}
		</form>
	</div>
	<div class="medium-6 columns">&nbsp;</div>
</div>
@endif
<!-- Container Content -->
<script type="text/javascript">
function confirmation(url, caption)
{
	if(confirm('Are you sure to ' + caption + ' this item?') == true)
	{
		window.location.replace(url);
		return true;
	}
}
</script>
<!-- Stops Container -->
@stop