app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Event::listen('auth.*', function($event){ });

// Authentication Routes...
$this->get('login', 'Auth\AuthController@showLoginForm');
$this->post('login', 'Auth\AuthController@login');
$this->get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);

// Registration Routes...
$this->get('register', 'Auth\AuthController@showRegistrationForm');
$this->post('register', 'Auth\AuthController@register');

//https://mattstauffer.co/blog/the-auth-scaffold-in-laravel-5-2
Route::get('/', ['middleware' => 'auth', 'as' => 'dashboard', 'uses' => 'DashboardController@index']);

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::get('/profile', ['middleware' => 'auth', 'as' => 'user_profile', 'uses' => 'UserController@profile']);

Route::post('/profile/{user_id}/update', ['middleware' => 'auth', 'as' => 'user_profile_update', 'uses' => 'UserController@update_profile']);

// Password Reset ejZ5yr
Route::get('/reset_user_password', ['as' => 'reset_user_password', 'uses' => 'UserController@reset_user_password']);
Route::post('/reset_user_confirm', ['as' => 'reset_user_confirm', 'uses' => 'UserController@reset_user_confirm']);

Route::group(['prefix' => 'api'], function () {
	Route::group(['prefix' => 'notification'], function () {
		Route::get('request', ['as' => 'request_notification', 'uses' => 'ServiceRequestController@notification']);
	});
	Route::group(['prefix' => 'search'], function () {
		//Route::get('category', ['as' => 'item_category_search', 'uses' => 'ItemCategoryController@search']);
		Route::get('item', ['as' => 'item_search', 'uses' => 'ItemController@search']);
	});
});

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function () {

	Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
	
	Route::group(['prefix' => 'user', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'users', 'uses' => 'UserController@index']);
		Route::get('create', ['as' => 'user_create', 'uses' => 'UserController@create']);
		Route::post('store', ['as' => 'user_store', 'uses' => 'UserController@store']);
		Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'UserController@edit']);
		Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'UserController@update']);

		Route::get('{user_id}/penalties', ['as' => 'user_penalties', 'uses' => 'UserController@penalties']);
	});

	Route::group(['prefix' => 'reports', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'reports', 'uses' => 'ReportController@index']);
		Route::post('generate', ['as' => 'report_generate', 'uses' => 'ReportController@generate']);
	});

	Route::group(['prefix' => 'dss', 'middleware' => 'admin'], function() {
		Route::get('/', ['as' => 'puchase_dss', 'uses' => 'HomeController@purchasedss']);
		Route::get('{id}/user', ['as' => 'user_dss', 'uses' => 'HomeController@userdss']);
		Route::get('{id}/item', ['as' => 'item_dss', 'uses' => 'HomeController@itemdss']);
	});

	Route::group(['prefix' => 'item', 'middleware' => 'admin'], function () {
		Route::get('/', ['as' => 'item', 'uses' => 'ItemController@index']);
		Route::get('create', ['as' => 'item_create', 'uses' => 'ItemController@create']);
		Route::post('store', ['as' => 'item_store', 'uses' => 'ItemController@store']);
		Route::get('{item_id}/edit', ['as' => 'item_edit', 'uses' => 'ItemController@edit']);
		Route::post('{item_id}/update', ['as' => 'item_update', 'uses' => 'ItemController@update']);
		Route::get('{item_id}/qrprint', ['as' => 'item_qrprint', 'uses' => 'ItemController@qrprint']);

		Route::group(['prefix' => 'category'], function () {
			Route::get('/', ['as' => 'item_category', 'uses' => 'ItemCategoryController@index']);
			Route::get('create', ['as' => 'item_category_create', 'uses' => 'ItemCategoryController@create']);
			Route::post('store', ['as' => 'item_category_store', 'uses' => 'ItemCategoryController@store']);
			Route::get('{item_category_id}/edit', ['as' => 'item_category_edit', 'uses' => 'ItemCategoryController@edit']);
			Route::post('{item_category_id}/update', ['as' => 'item_category_update', 'uses' => 'ItemCategoryController@update']);
		});

		Route::group(['prefix' => 'brand'], function () {
			Route::get('/', ['as' => 'item_brand', 'uses' => 'ItemBrandController@index']);
			Route::get('create', ['as' => 'item_brand_create', 'uses' => 'ItemBrandController@create']);
			Route::post('store', ['as' => 'item_brand_store', 'uses' => 'ItemBrandController@store']);
			Route::get('{item_brand_id}/edit', ['as' => 'item_brand_edit', 'uses' => 'ItemBrandController@edit']);
			Route::post('{item_brand_id}/update', ['as' => 'item_brand_update', 'uses' => 'ItemBrandController@update']);
		});
	});

	Route::group(['prefix' => 'service-request'], function () {
		Route::get('/', ['as' => 'service_request', 'uses' => 'ServiceRequestController@index']);
		Route::get('{id}/deny', ['as' => 'service_request_deny', 'uses' => 'ServiceRequestController@request_deny']);
		Route::get('{id}/cancel', ['as' => 'service_request_cancel', 'uses' => 'ServiceRequestController@request_cancel']);

		Route::post('{id}/approval', ['as' => 'service_request_approval', 'uses' => 'ServiceRequestController@request_approval']);

		Route::get('{id}/return', ['as' => 'service_request_return', 'uses' => 'ServiceRequestController@request_return']);

		Route::get('{id}/receipt', ['as' => 'service_request_receipt', 'uses' => 'ServiceRequestController@request_receipt']);

		Route::get('{id}/closed', ['as' => 'service_request_closed', 'uses' => 'ServiceRequestController@request_closed']);

		Route::group(['prefix' => 'item'], function () {
			Route::get('{id}', ['as' => 'service_request_items', 'uses' => 'ServiceRequestController@request']);
			Route::get('{id}/deny', ['as' => 'service_request_items_deny', 'uses' => 'ServiceRequestController@item_deny']);
			Route::get('{id}/cancel', ['as' => 'service_request_items_cancel', 'uses' => 'ServiceRequestController@item_cancel']);
			Route::get('{id}/approved', ['as' => 'service_request_items_approved', 'uses' => 'ServiceRequestController@item_approved']);

			Route::get('{request_id}/{brand_id}/{category_id}/assign', ['as' => 'service_request_assign_items', 'uses' => 'ServiceRequestController@assign_item_request']);
			Route::post('{request_id}/{brand_id}/{category_id}/assign-submit', ['as' => 'service_request_assign_items_submit', 'uses' => 'ServiceRequestController@assign_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return', ['as' => 'service_request_return_item', 'uses' => 'ServiceRequestController@return_item_request']);
			Route::post('{request_borrowed_item_id}/return-submit', ['as' => 'service_request_return_item_submit', 'uses' => 'ServiceRequestController@return_item_request_submit']);

			Route::get('{request_borrowed_item_id}/return-closed', ['as' => 'service_request_return_item_closed', 'uses' => 'ServiceRequestController@return_item_request_closed']);
			Route::post('{request_borrowed_item_id}/return-closed-submit', ['as' => 'service_request_return_item_closed_submit', 'uses' => 'ServiceRequestController@return_item_request_closed_submit']);
		});

		Route::get('create', ['as' => 'service_request_create', 'uses' => 'ServiceRequestController@create']);
		Route::post('store', ['as' => 'service_request_store', 'uses' => 'ServiceRequestController@store']);
		#Route::get('{user_id}/edit', ['as' => 'user_edit', 'uses' => 'ServiceRequestController@edit']);
		#Route::post('{user_id}/update', ['as' => 'user_update', 'uses' => 'ServiceRequestController@update']);
	});
});	

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use App\ServiceRequestReturnItem;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'active', 'reset'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setActiveAttribute($value)
    {
        return $value == 'on' ? 1 : 0 ;
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile', 'id', 'user_id');
    }

    public function requests()
    {
        return $this->hasMany('App\ServiceRequest');
    }

    public function getActiveStatusAttribute($value)
    {
        return ($this->active == 1) ? "Yes" : "No";
    }

    public function getRoleAliasAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "Administrator";
                break;
            case 'basic':
                return "Basic User";
                break;
            default:
                return "Unassigned";
                break;
        }
    }

    public function getActiveStatusLabelAttribute($value)
    {
        return ($this->active == 1) ? "<span class='label primary'>Yes</span>" : "<span class='label secondary'>No</span>";
    }

    public function getRoleAdminLabelAttribute($value)
    {
        switch ($this->role) {
            case 'admin':
                return "<span class='label primary'>Yes</span>";
                break;
            case 'basic':
                return "<span class='label secondary'>No</span>";
                break;
            default:
                return "<span class='label warning'>N/A</span>";
                break;
        }
    }

    public function getTotalPenaltiesAttribute()
    {
        $id = $this->id;

        #$count = ServiceRequestReturnItem::whereRequestReturnStatusId(2)->count();
        $count = ServiceRequestReturnItem::leftJoin('request', 'request_return_item.request_id', '=', 'request.id')
        ->where('request.user_id', $id)
        ->where('request_return_item.request_return_status_id', 2)
        ->count();

        return $count;
    }

    public function getCreatedAtAttribute($value)
   {
        return date('Y-m-d h:iA',strtotime($value));
   }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Item;
use App\User;
use App\ServiceRequest;
use DB;

class ReportController extends Controller
{
	public function index(Request $request)
    {
    	return view('reports.index');
    }

    public function generate(Request $request)
    {
    	$report_title = $request->report_type;
    	$report_date_start = date("Y-m-d 00:00:00", strtotime($request->report_date_start));
    	$report_date_end = date("Y-m-d 23:59:59", strtotime($request->report_date_end));
    	//$report_date_array = explode("/", $request->report_date);

    	if($report_title == 'items')
    	{
	    	$brands = Item::selectRaw("item_brand_id, 
	    		SUM(CASE WHEN status = 1 THEN 1 ELSE 0 END) AS available_count, 
	    		SUM(CASE WHEN status = 3 THEN 1 ELSE 0 END) AS defective_count, 
	    		SUM(CASE WHEN status = 2 THEN 1 ELSE 0 END) AS borrowed_count, COUNT(*) AS total_count")
	    	->whereBetween('created_at',[$report_date_start, $report_date_end])
	    	->groupBy('item_brand_id')->get();

	    	//dd($brands);

	    	$categories = Item::selectRaw("item_category_id, 
	    		SUM(CASE WHEN status = 1 THEN 1 ELSE 0 END) AS available_count, 
	    		SUM(CASE WHEN status = 3 THEN 1 ELSE 0 END) AS defective_count, 
	    		SUM(CASE WHEN status = 2 THEN 1 ELSE 0 END) AS borrowed_count, COUNT(*) AS total_count")
	    	->whereBetween('created_at',[$report_date_start, $report_date_end])
	    	->groupBy('item_category_id')->get();

	    	$items = Item::whereBetween('created_at',[$report_date_start, $report_date_end])
	    	->orderBy('created_at', 'DESC')
	    	->get();

	    	// $items_available = Item::selectRaw('*, count(*) as total')->whereStatus(1)->groupBy('item_brand_id')->get();
	    	// $items_defective = Item::selectRaw('*, count(*) as total')->whereStatus(3)->groupBy('item_brand_id')->get();
	    	// $items_borrowed = Item::selectRaw('*, count(*) as total')->whereStatus(2)->groupBy('item_brand_id')->get();
	    	//$data = compact('report_title', 'brands', 'categories', 'items_available', 'items_defective', 'items_borrowed');
	    	$data = compact('report_title', 'report_date_start', 'report_date_end', 'brands', 'categories', 'items');
	    }
	    elseif($report_title == 'users')
	    {
	    	$roles = User::selectRaw("role,
	    		SUM(CASE WHEN active = 1 THEN 1 ELSE 0 END) AS active_count, 
	    		SUM(CASE WHEN active = 0 THEN 1 ELSE 0 END) AS inactive_count, 
	    		COUNT(*) AS total_count")
	    	->whereBetween('created_at',[$report_date_start, $report_date_end])
	    	->groupBy('role')->get();

	    	$users = User::orderBy('email')
	    	->whereNotBetween('created_at',[$report_date_start, $report_date_end])
	    	->get();
	    	$data = compact('report_title', 'report_date_start', 'report_date_end', 'roles', 'users');
	    }
	    elseif($report_title == 'requests')
	    {
	    	$most_requested = ServiceRequest::selectRaw("item_brand.name AS name, COUNT(request_item.quantity) AS y")
                    ->leftJoin('request_item', 'request_item.request_id', '=','request.id')
                    ->leftJoin('item_brand', 'item_brand.id', '=','request_item.item_brand_id')
                    ->whereBetween('request.created_at',[$report_date_start, $report_date_end])
                    ->groupBy('item_brand.name')->orderBy(DB::raw('COUNT(request_item.quantity)'), "DESC")
                    ->limit(10)
                    ->get();
            $most_user = User::selectRaw('users.name, COUNT(*) y') 
                            ->leftJoin('request', 'request.user_id', '=','users.id')
                    		->whereBetween('request.created_at',[$report_date_start, $report_date_end])
                    		->limit(10)
                            ->get();

            $request_summary = ServiceRequest::selectRaw("
	    		SUM(CASE WHEN request_status_id = 1 THEN 1 ELSE 0 END) AS pending_count, 
	    		SUM(CASE WHEN request_status_id = 2 THEN 1 ELSE 0 END) AS approved_count, 
	    		SUM(CASE WHEN request_status_id = 3 THEN 1 ELSE 0 END) AS cancelled_count, 
	    		SUM(CASE WHEN request_status_id = 4 THEN 1 ELSE 0 END) AS denied_count, 
	    		SUM(CASE WHEN request_status_id = 5 THEN 1 ELSE 0 END) AS closed_count, 
	    		COUNT(*) AS total_count")
	    		->whereBetween('created_at',[$report_date_start, $report_date_end])->get();

            $requests_lists = ServiceRequest::whereBetween('created_at',[$report_date_start, $report_date_end])->get();

            $data = compact('report_title', 'report_date_start', 'report_date_end', 'request_summary', 'most_requested', 'most_user', 'requests_lists');
	    }
	    else
	    {
	    	abort(404);
	    }

    	return view('reports.generate', $data);
    }
}

resources/views/reports/partials/item.blade.php
<div class="row">
  <div class="small-12 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="4">Item Brand</th></tr>
        <tr>
          <th>Brand</th>
          <th>Available</th>
          <th>Borrowed</th>
          <th>Defective</th>
        </tr>
      </thead>
      <tbody>
        @if($brands->count() > 0)
          @foreach($brands as $brand)
              <tr>
                <td>{{ $brand->brand->name }}</td>
                <td>{{ $brand->available_count }} </td>    
                <td>{{ $brand->borrowed_count }} </td>   
                <td>{{ $brand->defective_count }} </td>   
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="4">Item Category</th></tr>
        <tr>
          <th>Category</th>
          <th>Available</th>
          <th>Borrowed</th>
          <th>Defective</th>
        </tr>
      </thead>
      <tbody>
        @if($brands->count() > 0)
          @foreach($categories as $category)
              <tr>
                <td>{{ $category->category->name }}</td>
                <td>{{ $category->available_count }} </td>    
                <td>{{ $category->borrowed_count }} </td>   
                <td>{{ $category->defective_count }} </td>   
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
</div>     
<div class="row">
  <div class="small-6 columns">
    
  </div>
</div>  
     <h5>Item Manifest</h5>
     <table>
       <thead>
         <tr>
          <th>Date Added</th>
          <th>ISBN</th>
          <th>Name</th>
          <th>Brand</th>
          <th>Category</th>
         </tr>
       </thead>
       <tbody>
         @foreach($items as $item)
          <tr>
            <td><small>{{ $item->created_at }}</small></td>
            <td>{{ strtoupper($item->isbn) }}</td>
            <td>{{ strtoupper($item->name) }}</td>
            <td>{{ strtoupper($item->brand->name) }}</td>
            <td>{{ strtoupper($item->category->name) }}</td>
          </tr>
         @endforeach
       </tbody>
     </table>

resources/views/reports/partials/request.blade.php
<div class="row">
  <div class="small-6 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="4">10 Most Requested Item Summary</th></tr>
        <tr>
          <th>Brand</th>
          <th>Requests</th>
        </tr>
      </thead>
      <tbody>
        @if($most_requested->count() > 0)
          @foreach($most_requested as $requested)
              <tr>
                <td>{{ $requested->name }}</td>
                <td>{{ $requested->y }} </td>    
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
  <div class="small-6 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="4">10 Users With Most Summary</th></tr>
        <tr>
          <th>Name</th>
          <th>Requests</th>
        </tr>
      </thead>
      <tbody>
        @if($most_user->count() > 0)
          @foreach($most_user as $user)
              <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->y }} </td>    
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="10">Request Status Summary</th></tr>
      </thead>
      <tbody>
        @if($request_summary->count() > 0)
          @foreach($request_summary as $request_status)
              <tr>
                <th style="width: 10%">Pending</th>
                <td style="width: 10%">{{ $request_status->pending_count }}</td>
                <th style="width: 10%">Approved</th>
                <td style="width: 10%">{{ $request_status->approved_count }}</td>
                <th style="width: 10%">Cancelled</th>
                <td style="width: 10%">{{ $request_status->cancelled_count }}</td>
                <th style="width: 10%">Denied</th>
                <td style="width: 10%">{{ $request_status->denied_count }}</td>
                <th style="width: 10%">Closed</th>
                <td style="width: 10%">{{ $request_status->closed_count }}</td>
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
</div>

<h5>Requests Manifest</h5>
 <table>
   <thead>
     <tr>
      <th>Requester</th>
      <th>Items</th>
      <th>Requested At</th>
      <th>Status</th>
     </tr>
   </thead>
   <tbody>

     @foreach($requests_lists as $req)
      <tr>
        <td style="width: 35%">{{ $req->user->name }}</td>
        <td>
          <ul>
            @if(App\ServiceRequestBorrowedItem::whereRequestItemId($req->id)->count()>0)
            @foreach(App\ServiceRequestBorrowedItem::whereRequestItemId($req->id)->get() as $borrowed_item)
              <li>{{ $borrowed_item->item->name }}</li>
            @endforeach
            @else
              <li>NO ITEM ASSIGNED</li>
            @endif
          </ul>
        </td>
        <td style="width: 15%">{{ $req->created_at }}</td>
        <td style="width: 10%">{{ $req->request_status->name }}</td>
      </tr>
     @endforeach
   </tbody>
 </table>

resources/views/reports/partials/user.blade.php
<div class="row">
  <div class="small-12 columns">
    <table border="1" cellspacing="0" cellpadding="0">
      <thead>
        <tr><th colspan="4">User Roles</th></tr>
        <tr>
          <th>Role</th>
          <th>Active</th>
          <th>Inactive</th>
        </tr>
      </thead>
      <tbody>
        @if($roles->count() > 0)
          @foreach($roles as $role)
              <tr>
                <td>{{ $role->role_alias }}</td>
                <td>{{ $role->active_count }}</td>
                <td>{{ $role->inactive_count }} </td>    
              </tr>   
          @endforeach
        @else
          <tr><td colspan="4"><center>No data</center></td></tr>
        @endif
      </tbody>
    </table>
  </div>
</div>   
<div class="row">
  <div class="small-6 columns">
    
  </div>
</div>  
     <h5>User Manifest</h5>
     <table>
       <thead>
         <tr>
          <th>Name</th>
          <th>Username</th>
          <th>Role</th>
          <th>Last Login</th>
         </tr>
       </thead>
       <tbody>
         @foreach($users as $user)
          <tr>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->role }}</td>
            <td>{{ $user->updated_at }}</td>
          </tr>
         @endforeach
       </tbody>
     </table>